# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  force
#    allowed_methods_listener:  true
#    routing_loader: true
    body_converter:
        enabled: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
    format_listener:
        rules:
            - { path: '^/$', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/', priorities: [ json, xml ], fallback_format: ~, prefer_extension: true }
