nelmio_api_doc:
    documentation:
        info:
            title: Kaso API
            description: App to retrieve kaso data
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^(?!(/connect|/login|/$))
