security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        hwi:
            id: hwi_oauth.user.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout_on_user_change: true
            anonymous: ~
            oauth:
                default_target_path: '%env(OAUTH_SUCCESS_REDIRECT_URL)%'
                resource_owners:
                    custom:    /login/check-custom
                login_path:   /login
                failure_path: /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
